Repository rutuja-39/WolfTrack5.0, pull requests merged in 2023-11, with the labels that each got.

#7 Adding job profile analyzer to extract skills
  Utils/jobprofileutils.py
  app.py
  database.db
  static/css/style.css
  templates/index.html
  templates/job_profile_analyze.html
  templates/layout/base.html
  templates/login.html
Labels: enhancement

#9 PR code changes from Issue_8_Enhancement to dev
  app.py
  database.db
  dbutils.py
  templates/admin_landing.html
  templates/layout/base.html
Labels: enhancement

#12 Dev merge
  Controller/home.py
  Login/admin_login.py
  Login/login.py
  Utils/__init__.py
  Utils/jobprofileutils.py
  Utils/main_login.py
  app.py
  database.db
  dbutils.py
  login_utils.py
  main.py
  static/css/style.css
  templates/admin_landing.html
  templates/admin_login.html
  templates/chat_gpt_analyzer.html
  templates/companies_list.html
  templates/find_jobs.html
  templates/home.html
  templates/index.html
  templates/job_profile_analyze.html
  templates/layout/base.html
  templates/login.html
  templates/resume_analyzer.html
  templates/signup.html
Labels: enhancement

#14 enhanced the UI
  app.py
  database.db
  static/css/login.css
  static/images/job_image.jpg
  static/images/jobportal-signup-placeholder.jpg
  templates/login.html
  templates/signup.html
Labels: enhancement

#23 PR changes from issue_17_Enhancement to dev
  app.py
  database.db
Labels: enhancement

#24 Dev
  Utils/jobprofileutils.py
  app.py
  database.db
  static/css/login.css
  static/images/job_image.jpg
  static/images/jobportal-signup-placeholder.jpg
  templates/job_profile_analyze.html
  templates/login.html
  templates/signup.html
Labels: enhancement

#25 Issue#13 enhancement
  app.py
  templates/job_search.html
  templates/job_search_resutls.html
  templates/layout/base.html
Labels: enhancement

#29 PR changes from Issue_17_Enhancement to dev
  app.py
  templates/layout/base.html
Labels: bug

#30 Issue 28 enhancement
  CITATION.cff
  app.py
  templates/home.html
  templates/index.html
  templates/job_search.html
  templates/job_search_results.html
Labels: enhancement

#31 Merge changes from CRUD_Operations branch to Dev
  app.py
  dbutils.py
  templates/home.html
Labels: enhancement

#32 Merge changes from dev to main
  CITATION.cff
  app.py
  dbutils.py
  sql/README.md
  sql/Schema.pdf
  sql/db-schema.mwb
  sql/ddl.sql
  sql/dml.sql
  templates/home.html
  templates/index.html
  templates/job_search.html
  templates/job_search_results.html
  templates/layout/base.html
Labels: enhancement

#42 PR changes from Issue_34_bug to dev
  app.py
  database.db
  dbutils.py
  templates/home.html
  templates/layout/base.html
Labels: bug

#46 MErge changes from CRUD branch to dev
  templates/home.html
  templates/layout/base.html
Labels: enhancement

#48 MErge changes from CRUD_Operations to dev branch
  app.py
  dbutils.py
  templates/home.html
Labels: enhancement

#50 PR changes from Issue_49_documentation to dev
  Controller/ResumeParser.py
  Controller/__init__.py
  Controller/chat_gpt_pipeline.py
  Controller/data.py
  Controller/send_email.py
  Controller/send_profile.py
  README.md
  app.py
  dbutils.py
  login_utils.py
Labels: documentation

#53 Dev
  README.md
  Rubrics.md
  UnitTesting/test_app.py
  UnitTesting/test_dbutils.py
  UnitTesting/test_loginutils.py
  docs/app.md
Labels: release
